server:
  port: 10000
spring:
  devtools:
    restart:
      enabled: true
      additional-paths: resources/**,static/**,templates/**
      exclude: data/**
  data:
    mongodb:
      database: SStudent
  freemarker:
    suffix: .ftl
    template-loader-path: classpath:/templates
    cache: false
  mvc:
    static-path-pattern: /static/**